name: Environment variables
on: push
jobs:
  run:
    runs-on: ubuntu-latest
    env:
      BRANCH: main
      ACTOR: ${{ github.actor}}
      USERNAME: ${{ vars.USERNAME}}
      PASSWORD: ${{ secrets.PASSWORD}}
    steps:
      - run: echo "${ACTOR}"